### ISSUE TITLE
Missing content on compliance

### ISSUE THREAD

**Issue by kylekirkby** [96boards/website#10]
https://github.com/96boards/website/tree/master/96boards.org/compliance I believe some content maybe misssing on this page.

5. Functional and Stress Testing
6. Compliance Report
7. Compliance Services 

Cheers,

Kyle

**Comment by sdrobertw** [comment]
@kylekirkby @shovanuk 
I will be addressing this issue.

CE, IE and EE compliance docs will be uploaded in several formats and made available with download links. I will include instructions for how to submit these compliance check lists to 96Boards team and steps to follow after submission.

**Comment by sdrobertw** [comment]
@kylekirkby @shovanuk 

Way behind on this. I am still waiting on feedback from various partners.

Will keep updated here.

**Comment by kylekirkby** [comment]
@sdrobertw Do we have the updated content for this page ? If not can we remove the links so that the page doesn't appear incomplete?

**Comment by kylekirkby** [comment]
@sdrobertw can we update the content on this page so we can close this issue?

**Comment by ric96** [comment]
Close as it looks like un-populated index items were removed.
