### ISSUE TITLE
Broken md code blocks: Problem with _posts/2019/04/2019-04-18-panfrost-rock960.md

### ISSUE THREAD

**Issue by ric96** [96boards/website#1009]
Code blocks on this website look weird... 
A couple of blocks after `2. Build Dependencies:` don't seem to render at all, but they render fine on GitHub and multiple IDEs on my computer.

And there are multiple blocks with unreadable contrast of light grey over white.

Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/blog/panfrost-rock960/

**Comment by kylekirkby** [comment]
@ric96 - do my recent updates resolve this issue? [https://www.96boards.org/blog/panfrost-rock960/](https://www.96boards.org/blog/panfrost-rock960/)

**Comment by ric96** [comment]
Yes, Thanks!
Closing.
