### ISSUE TITLE
Hikey970 Mechanical Issue

### ISSUE THREAD

**Issue by nmoshrefi** [96boards/website#1017]
Hello
I bought 2 Hikey970 boards and just received them.
the first Issue I noticed is diameter of spacer holes, all are 2.5mm, and big problem is to find M2.5 spacers to fix it on Acrylic sheet.
Strongly suggest to change Spacer Holes to 3mm Diameter, so will be much easier to find spacers for use board with fixing on Acrylic sheets.
![20190505213106](https://user-images.githubusercontent.com/42119925/57197492-2c84b300-6f7d-11e9-9f13-ddddf74ce81c.jpg)

going to find M2.5 Spacers for start ;)

Best regards
Nader

**Comment by Asvoria** [comment]
Well... 2.5mm is designed to hold using a plastic snap spacer. If you are using screw, then I see why you have a problem. Try use plastic snap spacer instead.

**Comment by ric96** [comment]
I don't know why this is in the website issue. please post this on the forums: https://discuss.96boards.org
