### ISSUE TITLE
Display members without the need for Javascript

### ISSUE THREAD

**Issue by morancj** [96boards/website#1082]
URL:  https://www.96boards.org/membership/

These are all empty:
```
96Boards Manufacturing Partners
96Boards Steering Committee
96Boards Partners
96Boards AI Partners
```

**Comment by kylekirkby** [comment]
Hi @morancj,

Could you please provide me with the browser you're using along with any plugins that you have installed which could potentially be blocking the javascript that pulls the members from https://www.linaro.org/assets/json/members.json?

Cheers,

Kyle

**Comment by morancj** [comment]
Hi @kylekirkby ,
I'm using Google's Chrome browser, `Version 75.0.3770.142 (Official Build) (64-bit)` with these extensions:
* [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en-GB)
* [EFF Privacy Badger](https://www.eff.org/privacybadger)

**Comment by kylekirkby** [comment]
Hi @morancj,

Thanks for the additional information. I've installed the above plugins and tested on the same browser and can see that no members are showing. Due to the way that members are being pulled in via javascript unless we change the way that this works the problem will persist. We could just statically generate the page on site build. I'll look into this!

BR,

Kyle

**Comment by morancj** [comment]
This 1/2MiB JS file? https://www.96boards.org/assets/package-members.js

**Comment by kylekirkby** [comment]
Thanks @morancj - looking into this now!

**Comment by morancj** [comment]
@kylekirkby Closed with no update on this?

**Comment by kylekirkby** [comment]
Hi @morancj,
Did this PR not fix your issue - https://github.com/96boards/website/pull/1087 ?

**Comment by morancj** [comment]
@kylekirkby I don't know, does it? The site looks OK now in Firefox with the same add-ons, still broken in Chrome (since updated to 76.0.3809.100-1). I'm happy to close this if you think requiring JS is OK. :)

**Comment by kylekirkby** [comment]
It would be nice to render member logos without the requirement of JS. We could pull the members.json file from linaro.org and build HTML instead. We'll have to take a look at updating Philip's member automation script to add this in!

**Comment by morancj** [comment]
@kylekirkby Thanks. :smile: 
I know it's hard to get logos to be perceived the same size, but in e.g. the case of the RedHat logo (2040x513+0+0 8-bit sRGB 76011B) and the Socionext logo (500x300+0+0 8-bit sRGB 19002B), the differences seem rather large. With whitespace removed, the RedHat logo renders to just over twice the width of Socionext's on my setup.

**Comment by kylekirkby** [comment]
Hi @morancj,

Not sure how I missed your response... Could you create another issue for this? I'm going to go ahead and close this one.

Cheers,

Kyle
