### ISSUE TITLE
Problem with 404.md

### ISSUE THREAD

**Issue by mdgramma** [96boards/website#1124]
https://www.96boards.org/wp-content/uploads/2015/02/HiKey_User_Guide_Rev0.2.pdf

The above link to lemaker hikey hardware manual doesn't work.

**Comment by sgermanserrano** [comment]
@mdgramma can you please point to where in the website is that link?

**Comment by mdgramma** [comment]
I would search for the file, this may exist in several points...

https://www.96boards.org/wp-content/uploads/2015/02/HiKey_User_Guide_Rev0.2.pdf

Miltos

From: Servando 
Sent: Monday, October 14, 2019 11:42 AM
To: 96boards/website 
Cc: mdgramma ; Mention 
Subject: {Disarmed} Re: [96boards/website] Problem with 404.md (#1124)

@mdgramma can you please point to where in the website is that link?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/96boards/website/issues/1124?email_source=notifications\u0026email_token=ADDJZIGA57W6IHR6CCN5HADQOQWHHA5CNFSM4I3RIBY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBDX7WA#issuecomment-541556696", "url": "https://github.com/96boards/website/issues/1124?email_source=notifications\u0026email_token=ADDJZIGA57W6IHR6CCN5HADQOQWHHA5CNFSM4I3RIBY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBDX7WA#issuecomment-541556696", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by kylekirkby** [comment]
Hi @mdgramma,

Where did you find this link? Is it on our website or did you have it bookmarked? 

Best regards,

Kyle

**Comment by kylekirkby** [comment]
Hi @mdgramma,

The file is available here - https://static6.arrow.com/aropdfconversion/ba467191defb7098ca30359852bde58042a709/hikey_user_guide_rev0.2.pdf

I think you may have found the file in an old forum post - https://discuss.96boards.org/t/how-to-enable-hi-fi-dsp-from-audio-subsystem/738

We will update the link so that others don't have the same issue that you were facing!

Best regards,

Kyle

**Comment by mdgramma** [comment]
It was on the website, came across while searching for 
HiKey 960 Documentation - User Guide

The others (Hardware etc I was able to locate, but that link failed).

Miltos

From: Kyle 
Sent: Tuesday, October 15, 2019 11:21 AM
To: 96boards/website 
Cc: mdgramma ; Mention 
Subject: {Disarmed} Re: [96boards/website] Problem with 404.md (#1124)

Hi @mdgramma,

Where did you find this link? Is it on our website or did you have it bookmarked?

Best regards,

Kyle

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/96boards/website/issues/1124?email_source=notifications\u0026email_token=ADDJZIAB7J3426MFVJBCBULQOV4RHA5CNFSM4I3RIBY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBH4AXI#issuecomment-542097501", "url": "https://github.com/96boards/website/issues/1124?email_source=notifications\u0026email_token=ADDJZIAB7J3426MFVJBCBULQOV4RHA5CNFSM4I3RIBY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBH4AXI#issuecomment-542097501", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by mdgramma** [comment]
Thanks.

It’s probably the likely cause.

Miltos

From: Kyle 
Sent: Tuesday, October 15, 2019 11:24 AM
To: 96boards/website 
Cc: mdgramma ; Mention 
Subject: {Disarmed} Re: [96boards/website] Problem with 404.md (#1124)

Hi @mdgramma,

The file is available here - https://static6.arrow.com/aropdfconversion/ba467191defb7098ca30359852bde58042a709/hikey_user_guide_rev0.2.pdf

I think you may have found the file in an old forum post - https://discuss.96boards.org/t/how-to-enable-hi-fi-dsp-from-audio-subsystem/738

We will update the link so that others don't have the same issue that you were facing!

Best regards,

Kyle

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/96boards/website/issues/1124?email_source=notifications\u0026email_token=ADDJZIAMXMSWXLD6RL2ICODQOV45XA5CNFSM4I3RIBY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBH4K7Y#issuecomment-542098815", "url": "https://github.com/96boards/website/issues/1124?email_source=notifications\u0026email_token=ADDJZIAMXMSWXLD6RL2ICODQOV45XA5CNFSM4I3RIBY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBH4K7Y#issuecomment-542098815", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
