### ISSUE TITLE
Should we add a bot running here?

### ISSUE THREAD

**Issue by sgermanserrano** [96boards/website#1165]
@ric96 @kylekirkby @morancj @pcolmer should we get the [Stale bot](https://github.com/probot/stale) running in the website repo? It might help keeping issues and PRs tidy

**Comment by pcolmer** [comment]
@sgermanserrano I don't have a problem with this suggestion. I think that the 96Boards team needs to add the appropriate configuration to the repo, though. I think that the team should be responsible for making the decisions ultimately.

**Comment by kylekirkby** [comment]
@sgermanserrano - +1 to @pcolmer's comment.

**Comment by ric96** [comment]
I don't have a problem as well. Let's have a discussion in the 96boards team sync and then add the stale bot.

**Comment by sgermanserrano** [comment]
@morancj there are few at the moment as @ric96 cleaned most yesterday, having it doesn't mean that we are not accepting issues but rather that orphaned ones (i.e. author does not reply or similar) are cleaned

**Comment by sgermanserrano** [comment]
Issues being addressed on a timely manner so bot not needed
