### ISSUE TITLE
errors in build_site.sh

### ISSUE THREAD

**Issue by sgermanserrano** [96boards/website#1191]
### Required information:
The `build_site.sh` script is throwing errors/warnings when being executed

### Description of the bug

As per [wiki](https://github.com/linaro-its/jekyll-build-container/wiki/Building-sites-that-use-multiple-git-repositories) I'm doing:
```
JEKYLL_ACTION='serve' NSBREPO2=~/96boards/documentation ./build-site.sh 
```
but the `documentation` repo is still being git cloned as the terminal shows:
```
NSBREPO2: https://github.com/96boards/documentation.git
/usr/local/bin/build-site.sh: line 179: get_repo_url: command not found
Cloning https://github.com/96boards/documentation.git
```
It looks like the `NSBREPO2` variable is not being used.

**Comment by pcolmer** [comment]
@sgermanserrano Can you please re-pull linaro-its/jekyll-build-container and try again? Thanks.

**Comment by sgermanserrano** [comment]
@pcolmer I'm using the `build_site.sh` script in `96boards/website` should that one be replaced?

**Comment by pcolmer** [comment]
@sgermanserrano no - the Docker container was incorrect. Just updating your copy of it should fix the problem.

**Comment by sgermanserrano** [comment]
@pcolmer thanks! it seems fine now
