### ISSUE TITLE
Compare Feature is Terrible

### ISSUE THREAD

**Issue by kentstroker** [96boards/website#1203]
The compare feature is horizontal not vertical. It is impossible to compare without scrolling up and down; I just gave up and took the time to leave a note but moving on to a website where I can more properly get information and not a headache from scrolling - a serious UX and UI blunder.

**Comment by pcolmer** [comment]
Thank you for your feedback. We will see what can be done to improve this feature.

In the meantime, there are buttons to swap the order in which the content is displayed. If you click on the right of the two buttons displayed at the top of the compare table:

![image](https://user-images.githubusercontent.com/1979931/71618113-26031580-2bb6-11ea-8fea-5370e6ad15de.png)

then this puts the boards across the top and the features down the left hand side.
