### ISSUE TITLE
Broken Image on Project list

### ISSUE THREAD

**Issue by shovanuk** [96boards/website#13]
@kylekirkby  can you fix the broken image on the project list?
https://github.com/96boards/website/tree/master/_96boards.org/_projects

**Comment by sdrobertw** [comment]
@shovanuk @kylekirkby 

Not only did a lot of images break, but all of my naming conventions were ignored and all my older images were removed. I spent a lot of time cropping and uploading these images and they were just removed without warning. File naming conventions were also ignored. 

IMO: These types of things need to be discussed before submitting and accepting such big changes. It will take a substantial amount of time on my end to repair what has happened.

Please also note, several images were placed in folder that do not match the mezzanine in questions. This will also need to be fixed.

**Comment by sdrobertw** [comment]
This should be fixed now?

@shovanuk @kylekirkby please close this issue, if you find it has been fixed.

Thanks!
