### ISSUE TITLE
Problem with 404.md

### ISSUE THREAD

**Issue by lalmiAhmed** [96boards/website#1300]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/404.html

**Comment by sgermanserrano** [comment]
hi, can you add some more information on the problem?

**Comment by lalmiAhmed** [comment]
this link is presented as "getting started" page for "Ultra96" (Arm-based, Xilinx Zynq UltraScale+(TM) MPSoC single board computer) , but the page not found ! 
the "Ultra96" product web page : https://www.hackster.io/xilinx/products/ultra96

**Comment by lalmiAhmed** [comment]
![Screenshot from 2020-07-16 11-13-27](https://user-images.githubusercontent.com/47051240/87659450-8114e800-c755-11ea-9508-e8f7c62b0729.png)

**Comment by sgermanserrano** [comment]
it looks like is pointing to the wrong place, I think you need [https://www.96boards.org/documentation/consumer/ultra96/ultra96-v2/getting-started/](https://www.96boards.org/documentation/consumer/ultra96/ultra96-v2/getting-started/)

**Comment by lalmiAhmed** [comment]
yes , that's the right page that should point to !

**Comment by ric96** [comment]
fixed by xilinx, closing.
