### ISSUE TITLE
Broken/misleading Link 

### ISSUE THREAD

**Issue by Thore-Krug** [96boards/website#1301]
On the Product page of the TB96-AI (https://www.96boards.org/product/tb-96ai/ ) in the `More Info`Section the Link labeled Schematic is broken/misleading

It links to: https://github.com/96boards/documentation/blob/master/som/tb-96ai/hardware-docs/files/avenger96-schematics.pdf

Which is not only a 404 Link but also would link to the wrong schematic Document if the file would be present. 

I assume the File was removed during Board bringup but the Link not fixed/removed.

**Comment by sgermanserrano** [comment]
@Thore-Krug thanks for pointing that out. Will be fixed when #1302 is merged

**Comment by Thore-Krug** [comment]
Thanks 🙂
