### ISSUE TITLE
Weird extensions for .md links on 96boards.org

### ISSUE THREAD

**Issue by sdrobertw** [96boards/website#133]
Some in IRC pointed out the .html extensions that are happening when reaching a .md point of the documentation.

ie:

https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/Debian.md.html

https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/OpenEmbedded.md.html

I guess many links have been saved without the .html and people are assuming they are broken.

Will we be keeping the .html extension?

Thanks.

**Comment by shovanuk** [comment]
Hi Robert

When we generate static sites some the .md files are converted into .html format. This is the only way we can render the page using Amazon S3. 

Thanks
Shovan
