### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by rbmistry** [96boards/website#137]
Seems like there are a bunch of missing links on page
https://www.96boards.org/product/dragonboard410c/

Under the section OS: Missing links are 
https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/Android.md
https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/Debian.md
https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/OpenEmbedded.md

Seems like same is true for HiKey, AOSP image link is broken as well.
Can someone please review these?

**Comment by sdrobertw** [comment]
It looks like these links are broken because they are not including the .html extension.

Once of us will look into this asap.

Thanks!

**Comment by sdrobertw** [comment]
@rbmistry This should be fixed now.

Could you please confirm and close the issue?

Thanks!

**Comment by shovanuk** [comment]
@kylekirkby 

Can we have redirect for these
https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/Android.md
https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/Debian.md
https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Downloads/OpenEmbedded.md

Correct links can be found on the page
https://www.96boards.org/product/dragonboard410c/

**Comment by kylekirkby** [comment]
Ok, will add these as redirects in my next PR.

Cheers,

Kyle

**Comment by shovanuk** [comment]
@kylekirkby can this be closed?

**Comment by kylekirkby** [comment]
@shovanuk This can be closed now
