### ISSUE TITLE
Latest board IMX7-96

### ISSUE THREAD

**Issue by ric96** [96boards/website#192]
add IMX7-96 to the latest boards list
here: https://www.96boards.org/products/

**Comment by shovanuk** [comment]
@kylekirkby can you look into this?

**Comment by sdrobertw** [comment]
It looks like this has been taken care of. i.mx7 boards is officially on the website, no problems.

Can we please close this issue?

@kylekirkby @shovanuk 

Thanks!

**Comment by ric96** [comment]
It is on the website, but the issue is that it doesn't show on the "latest board" on the front page or 9n the provided link.
