### ISSUE TITLE
Problem with _projects/faq.md

### ISSUE THREAD

**Issue by bathinirakesh** [96boards/website#204]
Please enter some details about the bug/issue so we can promptly resolve it.
I am using Dragonboard 410C ,it's not booting up
 Format: Log Type - Time(microsec) - Message - Optional Info
Log Type: B - Since Boot(Power On Reset),  D - Delta,  S - Statistic
S - QC_IMAGE_VERSION_STRING=BOOT.BF.3.0-00286
S - IMAGE_VARIANT_STRING=HAAAANAZA
S - OEM_IMAGE_VERSION_STRING=CRM
S - Boot Config, 0x000002e3
S - Core 0 Frequency, 0 MHz
B -      1549 - PBL, Start
B -      3497 - bootable_media_detect_entry, Start
B -    352730 - bootable_media_detect_success, Start
B -    352735 - elf_loader_entry, Start
B -    356887 - auth_hash_seg_entry, Start
B -    357095 - auth_hash_seg_exit, Start
B -    372916 - elf_segs_hash_verify_entry, Start
B -    433146 - PBL, End
B -    439810 - SBL1, Start
B -    502518 - pm_device_init, Start
D -     14701 - pm_device_init, Delta
B -    517646 - boot_flash_init, Start
D -         0 - boot_
it's stopped here only ,
can any body give suggestion to what i have to do next.

**Comment by Mani-Sadhasivam** [comment]
Hi @bathinirakesh ,

Can you please raise this question in forum?
https://discuss.96boards.org/c/products/dragonboard410c

Submit issue to website if you find something wrong with the contents. All of the technical discussions around 96Boards happens in forum only.

Thanks,
Mani

**Comment by sdrobertw** [comment]
@bathinirakesh has you issue been addressed? If so, would you mind closing this issue?

I agree with @Mani-Sadhasivam ; this issue should be raised on 96Boards forums:

https://discuss.96boards.org/c/products/dragonboard410c

*This issue will be labeled as inactive and closed in due time without a response.

Thanks!
