### ISSUE TITLE
Products links are not categorised

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [96boards/website#205]
Links to all products are not under appropriate categories.

For instance, link to Dragonboard410c is:
https://www.96boards.org/product/dragonboard410c/ 

But it should be: 
https://www.96boards.org/product/ce/dragonboard410c/

Also, the above link redirects to the former. Don't know whether this is
intentional or not!

**Comment by shovanuk** [comment]
@Mani-Sadhasivam 

This is intentional. We moved from /product/ce to /product/ to keep the URLs simple and easy to access. 

Thanks

**Comment by sdrobertw** [comment]
If this is how things are to remain, can we please close this issue?

Thanks.
