### ISSUE TITLE
Problem with _projects/view/deeplearning/README.md

### ISSUE THREAD

**Issue by ssudhe** [96boards/website#225]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/projects/deeplearning/

Can you please complete the ReadMe.txt and also the complete project.
https://github.com/gholamlooAli/tf410c

Looking for the bazel binary that is built for DB410C with Debian linaro. 
Right now, I am editing compiling Bazel for aarch64. It would help us a lot if you can please share the binaries.

**Comment by Mani-Sadhasivam** [comment]
Hi @ssudhe ,

Can you please open the same issue in https://github.com/gholamlooAli/tf410c ?

By this way the author of that project will get quick notification!

**Comment by Mani-Sadhasivam** [comment]
This issue is not related to 96Boards contents. Hence we can close it!
