### ISSUE TITLE
Problem with _product/ce/hikey960/README.md

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [96boards/website#242]
Wrong board vendors specified for this board as below:

`The board is provided by Archermind and LeMaker through multiple channels (see links on right).`

URL:  https://www.96boards.org/product/hikey960/

**Comment by shovanuk** [comment]
Update?

**Comment by Mani-Sadhasivam** [comment]
This board is indeed sold by Archermind and Lemaker. Sorry for the noise!
