### ISSUE TITLE
Problem with _product/ie/orangepi-i96/README.md

### ISSUE THREAD

**Issue by gkelly** [96boards/website#277]
URL:  https://www.96boards.org/product/orangepi-i96/

Download links for OS images are all 404.

**Comment by sdrobertw** [comment]
Hello, @gkelly 

For now, please visit: https://www.96boards.org/documentation/IoTEdition/orangepi-i96/downloads/
for OS options and non-broken links.

Our team is currently working to resolve all broken URL's on both website and documentation repositories! You should expect us to be back up and running within the week. Thank you very much for your observations and we apologize for the inconvenience.

**Comment by shovanuk** [comment]
This is now fixed
