### ISSUE TITLE
Links that need fixing

### ISSUE THREAD

**Issue by pcolmer** [96boards/website#301]
With the incoming re-working of how redirects are being handled, it will no longer be possible for content to have links that rely on redirects in order for the links to work (since the link checker won't be able to use the new rules). All content must point to valid destinations. This is beneficial for site users because it avoids additional redirects to reach the desired end page.

With that in mind, the following links will break once that change is enforced:

    /blog/15-10-alpha/index.html:
       /products/ce/hikey/index.html
       /products/ce/dragonboard410c/index.html
    /blog/96boards-96brews-automated-home-brewing/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/96boards-box-experience-guide-1/index.html:
       /products/ce/hikey/index.html
       /products/ce/dragonboard410c/index.html
       /products/ce/bubblegum96/index.html
       /tag/openhours/index.html
    /blog/96boards-box-experience-guide-2/index.html:
       /tag/openhours/index.html
    /blog/96boards-box-experience-guide-3/index.html:
       /products/ce/hikey/index.html
       /products/ce/dragonboard410c/index.html
       /products/ce/bubblegum96/index.html
       /tag/openhours/index.html
    /blog/96boards-box-experience-guide-5/index.html:
       /products/accessories/power/index.html
       /products/mezzanine/linker-mezzanine-starter-kit/index.html
       /products/mezzanine/grove-starter-kit/index.html
       /tag/openhours/index.html
    /blog/96boards-ce-temp-using-level-shifters-2-line-displays/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/96boards-magic-8-ball-digital-hourglass/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/96boards-media-server/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/96boards-openhours-12-recap/index.html:
       /db410c-getting-started/Quickstart/README.md/index.html
    /blog/96boards-openhours-15-recap/index.html:
       /products/mezzanine/sensors-mezzanine/index.html
    /blog/96boards-openhours-d3-designcore-camera-mezzanine/index.html:
       /product/d3-designcore-camera-mezzanine/index.html
    /blog/96boards-openhours-session-4-recap/index.html:
       /products/accessories/adapter/index.html
       /tag/openhours/index.html
    /blog/96boards-openhours-session-5-recap/index.html:
       /tag/openhours/index.html
    /blog/96boards-openhours-session-6-recap/index.html:
       /tag/openhours/index.html
    /blog/96boards-openhours-wrap-up-week-3/index.html:
       /tag/openhours/index.html
    /blog/96boards-updates-development-aosp/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/96boards-vu-meter-part-1/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/bringing-standardization-linux-gpio-96boards/index.html:
       /products/ce/dragonboard410c/index.html
       /products/ce/hikey/index.html
    /blog/ce-iot-using-sensors/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/community-mezzanine-board/index.html:
       /product/grove-starter-kit/index.html
       /product/uarts/index.html
    /blog/d3-designcore-camera-mezzanine-and-openhours/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/demo-96boards-openhours-hikey960-launch/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/diy-drone-featuring-gumstix-96boards-take-flight-openhours/index.html:
       /product/aerocore/index.html
    /blog/dragonboard-410c-demos/index.html:
       /products/ce/dragonboard410c/index.html
    /blog/fritzing-part-96boards-ce/index.html:
       /products/ce/hikey/index.html
       /products/ce/dragonboard410c/index.html
       /products/ce/bubblegum96/index.html
    /blog/google-assistant-96boards-instructions/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/google-assistant-using-96boards-intro/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/googles-magenta-kernel-hikey-960/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/hikey960-takes-96boards-openhours/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/ibm-cognitive-hackathon-india-pune-bangalore-2017/index.html:
       /products/ce/dragonboard410c/index.html
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/laser-cutting-96boards-daniel-t/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/lfelc-part1/index.html:
       /products/ce/dragonboard410c/index.html
       /products/ce/hikey/index.html
       /products/ce/bubblegum96/index.html
       /products/mezzanine/stm32sensor/index.html
       /products/mezzanine/uarts/index.html
       /products/mezzanine/sensors-mezzanine/index.html
       /products/mezzanine/linker-mezzanine-starter-kit/index.html
    /blog/modding-arrows-audio-mezzanine-96boards/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/new-96boards-mezzanine-template-for-kicad/index.html:
       /products/mezzanine/uarts/index.html
       /products/mezzanine/sensors-mezzanine/index.html
    /blog/openhours-community-minute-testing-96boards-audio-mezzanine-jean-marc-jobin/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/part-1-home-surveillance-project-96boards/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/part-2-home-surveillance-project-96boards/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/part-3-home-surveillance-project-96boards/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/part-4-home-surveillance-project-96boards/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/part-5-home-surveillance-project-96boards/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/path-libmraa-96boards-part-1/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/path-libmraa-96boards-part-2/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/path-libmraa-96boards-part-3/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/playing-96boards-sensors-mezzanine-jean-marc-jobin/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/project-big-button-barry-byford/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/qualcomm-maker-month-contest/index.html:
       /products/ce/dragonboard410c/index.html
    /blog/ramblings-mezzanine-boards/index.html:
       /products/mezzanine/stm32sensor/index.html
       /products/mezzanine/linker-mezzanine-starter-kit/index.html
       /products/mezzanine/uarts/index.html
       /products/mezzanine/sensors-mezzanine/index.html
       /products/mezzanine/grove-starter-kit/index.html
       /product/aerocore/index.html
    /blog/recap-96boards-openhours-23-season-2-announcement-sneak-peak/index.html:
       /products/mezzanine/sensors-mezzanine/index.html
       /products/mezzanine/stm32sensor/index.html
       /product/aerocore/index.html
    /blog/recap-of-the-96boards-openhours-18/index.html:
       /products/mezzanine/sensors-mezzanine/index.html
    /blog/recap-of-the-96boards-openhours-20-dragonboard-410c-mini-series-part-2/index.html:
       /products/mezzanine/grove-starter-kit/index.html
    /blog/recap-of-the-96boards-openhours-21-dragonboard-410c-mini-series-part-3/index.html:
       /products/mezzanine/uarts/index.html
    /blog/reference-software-platform-15-12-release/index.html:
       /products/ce/hikey/index.html
       /products/ce/dragonboard410c/index.html
    /blog/servo-motor-control/index.html:
       /products/ce/hikey/index.html
    /blog/st-system-level-esd-protection/index.html:
       /product/stm32sensor/index.html
       /newsletter/index.html
       /newsletter/digest/index.html
    /blog/the-beginning-of-96boards/index.html:
       /products/ce/hikey/index.html
       /products/ce/dragonboard410c/index.html
    /blog/welcome-2017-year-96boards/index.html:
       /product/linker-mezzanine-starter-kit/index.html
       /product/stm32sensor/index.html
       /documentation/README.md/index.html
       /documentation/Extras/ContributionPolicy.md/index.html
       /project/cecase/index.html
       /tutorial/running-kvm-guest-hikey/index.html
       /newsletter/digest/index.html
       /product/b2260/index.html
       /newsletter/index.html
    /blog/welcome-2018/index.html:
       /newsletter/index.html
       /newsletter/digest/index.html
    /product/ethernetcard/index.html:
       /mezzanine/index.html
    /products/mezzanine/index.html:
       /mezzanine/index.html
    /projects/KVM/index.html:
       /tutorial/running-kvm-guest-hikey/index.html
    /tutorials/dragonboard410c/index.html:
       /tutorials/index.html

**Comment by kylekirkby** [comment]
Fixing them now :)

**Comment by kylekirkby** [comment]
Fixed in this PR - https://github.com/96boards/website/pull/302

@pcolmer @shovanuk
