### ISSUE TITLE
Problem with _product/ce/bubblegum-96/README.md

### ISSUE THREAD

**Issue by shovandigital** [96boards/website#313]
Additional information table has a couple of ?? Can this be fixed?
---
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/product/bubblegum-96/

**Comment by Mani-Sadhasivam** [comment]
Fixed in #455

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Please close this issue!
