### ISSUE TITLE
Problem with _product/ce/dragonboard820c/README.md

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [96boards/website#365]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/product/dragonboard820c/

> Integrated Dual ISP with support for 3 image sensors up to 28MP

According to [QDN documentation](https://developer.qualcomm.com/hardware/dragonboard-820c) only dual channel CSI interface (2L + 4L) is present on DB820c. Does 3 here means one additional virtual channel?

**Comment by todortomov** [comment]
2L+4L-MIPI CSI are available on the high-speed connector.
DB820c also has one onboard 96boards Camera Interface 4-L MIPI CSI.
So in total it supports up to three image sensors.

> Integrated Dual ISP with support for 3 image sensors up to 28MP
This is correct (bearing in mind that we do not support ISP processing for Bayer format).

**Comment by Mani-Sadhasivam** [comment]
Thanks @todortomov for clarification!
