### ISSUE TITLE
Problem with _product/ce/hikey960/README.md

### ISSUE THREAD

**Issue by j-catala** [96boards/website#375]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/product/hikey960/

Seeedstudio link outdated, new one --> https://www.seeedstudio.com/HiKey-960-Development-Board-4GB-RAM-Version-p-3028.html
Switch Science link outdated, new one --> https://www.switch-science.com/catalog/3545/
Ali Express page that is unreachable (404),
Alpha Star "Buy it now" button links to Ali Express page that is unreachable (404)

**Comment by kylekirkby** [comment]
Hi Joel, the links have been updated! Can you please verify this is fixed so that we can close the issue?

**Comment by sdrobertw** [comment]
@j-catala @kylekirkby Since this issue has been fixed and we have not received a response in several days, the issue will be closed. If you have any more questions or feel your issue has not been resolved. Please feel free to reopen this issue, or create another one.

Thanks!
