### ISSUE TITLE
Project Contibution _projects/contribute.md

### ISSUE THREAD

**Issue by kinscore** [96boards/website#490]
Title: Tourmalet
Description: Portable Multimedia player using DragonBoard 410c and a 1080p touchscreen
Bill of Materials:
DragonBoard 410c
Tianma TL055VVMS15-00 touchscreen
3D printed casing (STL files published)
Touchscreen adapter boards (schematics, Gerbers published)
battery, contacts

https://github.com/synaptics-cpt/tourmalet

**Comment by sdrobertw** [comment]
@ric96  we need to figure out a way to streamline project submission through this area.

Please advise.

**Comment by ric96** [comment]
@sdrobertw @kylekirkby is the project submission form at https://www.96boards.org/projects/submit/ ready?

**Comment by sdrobertw** [comment]
@ric96 it is, but we would still need to manually input ourselves each time one is submitted.

**Comment by sdrobertw** [comment]
thanks @ric96

**Comment by ric96** [comment]
@kinscore can you submit your project via the form on this page: https://www.96boards.org/projects/submit/
The form should  come up once you click the "Submit a Project" Button
Thanks!

**Comment by kinscore** [comment]
I clicked "submit a project" and filled out the form. I noticed that "project type" and "project category" have dummy choices, "project thumbnail" is not optional, despite the informational text, and the form seems to have little relation to the instructions on the same page (should I submit a pull request in addition to the form?).

**Comment by ric96** [comment]
@kinscore no need for the pull request, the form is its separate thing, the "Send a Pull Request" way of submitting a project MIGHT be depreciated down the line.

**Comment by ric96** [comment]
@kinscore if you don't have a project thumbnail at hand feel free to repeat the "Project Images" file for now and submit the form

**Comment by kinscore** [comment]
I used a smaller version of one of the project images as the thumbnail and submitted the form. Has it been received?

**Comment by ric96** [comment]
@kinscore received, should be up in a day or so
