### ISSUE TITLE
Project contribution to 96Boards

### ISSUE THREAD

**Issue by kyrofa** [96boards/website#6]
**Title:** ROS prototype to production on Ubuntu Core.
**Description:** Step-by-step multi-part series for developing a ROS prototype for the Turtlebot 2 controlled by an Intel NUC or a DragonBoard, and creating an Ubuntu Core image with the prototype preinstalled.
**Bill of materials:** Turtlebot 2 and a DragonBoard.

**Comment by sdrobertw** [comment]
@kyrofa Thank you for the submission! What did you think of the process? Any issues?

**Comment by kyrofa** [comment]
@sdrobertw easy peasy. There's a little bit of a disconnect between the code and what's rendered on the website, though, so the process ended up being like this:

1. Visited https://www.96boards.org/projects/ . Thought "Yeah, I'd like to submit my project. Okay, 'for instructions for how to submit,' sure" and clicked "Submit a project."
2. "Okay... github account check. Fork this repository... wait... what repository?" Hit back button, found link to repo, opened in another tab, forked, then went back to "Submit a project" to continue reading.
    - Feedback: Might want to consider including a link to the project in github in SUBMIT.md when you discuss forking the project.
3. SUBMIT.md (which is the only visible part of the workflow on the website) goes straight from forking to creating your project dir without mentioning creating an issue first. However, CONTRIBUTE.md DOES mention creating an issue first. So I made an issue just in case.
    - Feedback: you might want to consider consolidating those two documents, or at least making them consistent on the guidance they provide.
4. Followed the rest of SUBMIT.md with no issues.

**Comment by kyrofa** [comment]
Ah, just noticed "contribute" next to "Submit a project." What is the difference?

**Comment by kyrofa** [comment]
I also just realized that nothing discusses images, although I see some in the Template. How do those work?

**Comment by sdrobertw** [comment]
Yes! Thank you for pointing this out.

1) We are still working out frequency of website rendering, currently webmaster has it set for manual updates. We will eventually implement an automatic cache reset to happen several times a day.

2) Each GitHub rendered page will have links to "Edit this page on Github". We think this will make people more aware of the fact it is being rendered up.

3) Contribution is supposed to feel like more of a "Guidelines" while Submit a project is more like "instructions". Will have to find a better way to stream like this to make it easier for those who are not as in tuned with GitHub! 

Thanks for the observations, I would like to keep this Issue open for those who might stumble across until I have this fixed. :)

**Comment by ric96** [comment]
looks like the fix was merged, closing
