### ISSUE TITLE
mini USB came loose

### ISSUE THREAD

**Issue by gezamboni** [96boards/website#671]
Two months ago I received a Sensor Mezzanine Board I bought to be used with my Dragonboard 410c. When I unpluged the mini USB cable off the board connector it came loose.
I would like to know  how can you exchange this broken boatd for a new one. 
I think something is wrong with the board because it is not possible that a connector comes loose from a board in the first use of it. 
![img_0240](https://user-images.githubusercontent.com/38640418/43842580-0dd07a62-9afc-11e8-918c-1c81bbc3bf34.JPG)
![img_0237](https://user-images.githubusercontent.com/38640418/43842581-0df15d72-9afc-11e8-9f24-f3ae85903f83.JPG)
![img_0239](https://user-images.githubusercontent.com/38640418/43842582-0e123f7e-9afc-11e8-8388-25742130dc7c.JPG)
![img_0236](https://user-images.githubusercontent.com/38640418/43842583-0e31c5ba-9afc-11e8-86c5-6875fc7a7517.JPG)
![img_0234](https://user-images.githubusercontent.com/38640418/43842584-0e50828e-9afc-11e8-9c98-512c5c9eb1c3.JPG)
![img_0235](https://user-images.githubusercontent.com/38640418/43842585-0e715d92-9afc-11e8-8e27-ba6e90e3be43.JPG)
Remain waiting for your answer

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Can you please look into this?

**Comment by kylekirkby** [comment]
Any update on this guys ? @sdrobertw @Mani-Sadhasivam @ric96

**Comment by ric96** [comment]
Not a documentation related issue, OP should contact SeeedStudio. Also post is a year old. closing
