### ISSUE TITLE
Problem with download pdf

### ISSUE THREAD

**Issue by wjy7717** [96boards/website#709]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/404.html

HiKey Hardware User Manual 
http://www.lemaker.org/cn/product-hikey-download-52.html

**Comment by Mani-Sadhasivam** [comment]
@ric96 Can you please check with Lemaker on the HiKey hardware user manual.

@wjy7717 Meantime, you can refer our markdown based reference manual [here](https://www.96boards.org/documentation/consumer/hikey/hikey620/hardware-docs/hardware-user-manual.md.html).

**Comment by ric96** [comment]
hardware user manual link is working for me.
Closing
