### ISSUE TITLE
uartserial: Buy link is broken (and there's only one link)

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/website#777]
The "Buy" link is broken. It lands on the seeed front page instead of landing at https://www.seeedstudio.com/96Boards-UART-p-2525.html . Unfortunately it
vectors through linaro.co for link shortening so I'm not clear how to fix...

URL:  https://www.96boards.org/product/uartserial/

**Comment by kylekirkby** [comment]
Hi @daniel-thompson, I've updated the broken links on link.linaro.org. If you don't have an account then raise a ticket with ITS and they'll add you.

Closing :)
