### ISSUE TITLE
sensors-mezzanine: Buy link is broken

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/website#778]
The "Buy" links are broken. They land on the seeed front page instead of landing at https://www.seeedstudio.com/96Boards-Sensors-p-2617.html and https://www.seeedstudio.com/Grove-Starter-Kit-for-96Boards-p-2618.html respectively. Unfortunately both
vector through linaro.co for link shortening so I'm not clear how to fix...

Note that *both* the links are broken

URL:  https://www.96boards.org/product/sensors-mezzanine/

**Comment by kylekirkby** [comment]
Hi @daniel-thompson, can you please provide the current working link to the product pages - I can replace the short links with the correct links as it appears that SeeedStudio have redirected the pages to the homepage.

Many thanks,

Kyle

**Comment by kylekirkby** [comment]
Hi @daniel-thompson, I've updated the broken links on link.linaro.org. If you don't have an account then raise a ticket with ITS and they'll add you. 

Closing :)

**Comment by daniel-thompson** [comment]
It looks like the Seeed Studio website is not compatible with our link shortner (the shortener URL does not seem broken in wget but the Seeed website appears to detect 301 referrals and handle them differently to regular links).

Should we just switch the markdown to use normal URLs? Does that hurt out analytics much?

**Comment by kylekirkby** [comment]
That particular link has over 6000 clicks recorded in YOURLS. It would be good to keep it as is - it's been working before so I guess they have just updated something their end... let me take a look.

**Comment by kylekirkby** [comment]
http://link.linaro.org/1KnV9TA this works for me. Does it still work for you ?

**Comment by kylekirkby** [comment]
It only appears to break when using https - http://linaro.co/1KnV9TA works but https://linaro.co/1KnV9TA does not. We can just update the protocol to http...

**Comment by kylekirkby** [comment]
https://github.com/96boards/website/pull/779

**Comment by kylekirkby** [comment]
Fixed
