### ISSUE TITLE
Do we need this file

### ISSUE THREAD

**Issue by shovanuk** [96boards/website#8]
@sdrobertw Do we need this file on the root folder?
https://github.com/96boards/website/blob/master/96boards.org/Products/dragonboard410c-buy.md

**Comment by sdrobertw** [comment]
This file is used in section of current DB410c landing page. I want to move it, but did not want to break website.

We need it, but I would like to move into DB410c documentation repository.

**Comment by sdrobertw** [comment]
Removed
