### ISSUE TITLE
Problem with openhours/about/README.md

### ISSUE THREAD

**Issue by tdhammer** [96boards/website#874]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/openhours/about/

The age has not been updated for switch to Zoom.

**Comment by sdrobertw** [comment]
@tdhammer there should have been an update to the OpenHours page. Are you saying there are stil links to the BlueJeans channel? IIRC, it should now forward people to Zoom and YouTube stream.

**Comment by sdrobertw** [comment]
@tdhammer I retract my last comment! 

This is correct, it appears the FAQ needs to be updated! Very nice observation and thank you very much for bringing this to my attention. 

We will try to get this updated soon.

**Comment by ric96** [comment]
fixed with #1164
