### ISSUE TITLE
Shiratech lte with dragonboard 410c

### ISSUE THREAD

**Issue by Eugene0469** [96boards/website#965]
Hello. I have the shiratech LTE mezzanine board together with a dragon board 410c. I followed the setup tutorial that comes with the board but the board never connects to the mobile broadband network, it just keeps showing icon. I have tried it with three different sim cards to no avail. What could be the problem?

**Comment by sgermanserrano** [comment]
@Eugene0469 please post your question at the [96 boards db410c forum](https://discuss.96boards.org/c/products/dragonboard410c) or the [96boards mezzanine forum](https://www.96boards.org/products/mezzanine/). The issues on this repo are tied to problems with the website itself.

I'd also suggest joining [96boards Discord](https://discord.gg/x5uMn5d)

**Comment by ric96** [comment]
Closing since issue not related to the website repo
